// Code generated by chapati; DO NOT EDIT.

package example

import (
	jen "github.com/dave/jennifer/jen"
	"io"
)

func CurriedWithImport(c jen.Code) func(io.Writer) error {
	return func(w io.Writer) error {
		return withImport(c, w)
	}
}
